---
title: "Untitled"
author: "AS"
date: "December 4, 2017"
output: pdf_document
---

# from the deleted file article hints (somewhen created in winter 2016/17)
INTRODUCTION:

(Lorenz et al., 2016)
Lack of information on small water bodies (SWB)
Golla & Horney (unpublished data):
	97% of the 321,128 German lentic WB are smaller than 0.05km² surface area
	91.3% of the 544,967 German streams <3m width

Questions: lotic SWB: 	How did they find out?
				How does this translate into catchment area ? 
				Will their paper be finished? How to cite them?

Include (Biggs et al., 2016) 

Have a look through (Ulrich et al., 2015). Why do they have so much information on Bavaria?


Agricultural land use effects ecological conditions of aquatic systems (Feld, 2013)


METHODS:

Account for geographical effects in (Feld, 2013):
Ecoregion,
longitude/latitude (decimal degrees) - https://en.wikipedia.org/wiki/Decimal_degrees
altitude (m.a.s.l.)
country (Germany, France)

Boosted Regression Trees – vignette? (Elith and Leathwick, 2016)
allows for correlated predictor variables

DISCUSSION:

data originates from governmental monitoring programs, grab samples  → underestimating the real effects probably (Malaj et al., 2014)

Anthropogenic factors like application regime and intensity are hard to address

Criticize (Van Dijk et al., 2013) because of the usage of lm  (+ high variability + justification), made up groups, 
